ALTER TABLE users ADD COLUMN email TEXT NOT NULL;
ALTER TABLE users ADD COLUMN password_hash TEXT NOT NULL;
ALTER TABLE users ADD COLUMN locked_at TIMESTAMP WITH TIME ZONE DEFAULT null;
ALTER TABLE users ADD COLUMN failed_login_attempts INT DEFAULT 0 NOT NULL;
